# Autogenerated with SMOP 
# CartToSph.m
import math
import numpy as np
from zerotwopi import zerotwopi

def carttosph(cn,ce,cd):

    '''
    carttosph converts from cartesian to spherical coordinates 
    
       [trd,plg] = carttosph(cn,ce,cd) returns the trend (trd)
       and plunge (plg) of a line for input north (cn), east (ce), 
       and down (cd) direction cosines
    
       NOTE: Trend and plunge are returned in radians
    
       CartToSph uses function ZeroTwoPi
    
    MATLAB script written by Nestor Cardozo for the book Structural 
    Geology Algorithms by Allmendinger, Cardozo, & Fisher, 2011. If you use
    this script, please cite this as "Cardozo in Allmendinger et al. (2011)"
    
    Converted to python by Ben Melosh Sept 28th 2022
    '''



    # Plunge (see Table 2.1)
    plg = np.arcsin(cd)

    # Trend
    # If north direction cosine is zero, trend is east or west
    # Choose which one by the sign of the east direction cosine
    if cn == 0.0: 
        if ce < 0.0:
            trd = 3.0/2.0*np.pi #% trend is west
        else:
            trd = np.pi/2.0 # trend is east

    # Else use Table 2.1
    else:
        trd = np.arctan(ce/cn) 
        if cn < 0.0:
            #Add pi 
            trd = trd+np.pi

        # Make sure trd is between 0 and 2*pi
        trd = zerotwopi(trd)

    return [trd,plg]

