# Autogenerated with SMOP 
from smop.core import *
# MultMatrix.m

    
@function
def MultMatrix(a=None,b=None,*args,**kwargs):
    varargin = MultMatrix.varargin
    nargin = MultMatrix.nargin

    #MultMatrix multiplies two conformable matrices
    
    #   USE: c = MultMatrix(a,b)
    
    #   Matrix a premultiplies matrix b to produce matrix c, as in the equation
#   c = ab
    
    #   NOTE: This function is only for illustration purposes. To multiply 
#   matrices in MATLAB use the * operator (e.g. c = a*b)
    
    #MATLAB script written by Nestor Cardozo for the book Structural 
#Geology Algorithms by Allmendinger, Cardozo, & Fisher, 2011. If you use
#this script, please cite this as "Cardozo in Allmendinger et al. (2011)"
    
    aRow=size(a,1)
# MultMatrix.m:16
    
    aCol=size(a,2)
# MultMatrix.m:17
    
    bRow=size(b,1)
# MultMatrix.m:18
    
    bCol=size(b,2)
# MultMatrix.m:19
    
    #If the multiplication is conformable
    if aCol == bRow:
        #Initialize c
        c=zeros(aRow,bCol)
# MultMatrix.m:24
        for i in arange(1,aRow).reshape(-1):
            for j in arange(1,bCol).reshape(-1):
                for k in arange(1,aCol).reshape(-1):
                    c[i,j]=dot(a[i,k],b[k,j]) + c[i,j]
# MultMatrix.m:28
        #Else report an error
    else:
        error('Error: Inner matrix dimensions must agree')
    
    return c
    
if __name__ == '__main__':
    pass
    