# Autogenerated with SMOP 
from smop.core import *
# PureShear.m

    
@function
def PureShear(pts=None,st1=None,ninc=None,*args,**kwargs):
    varargin = PureShear.varargin
    nargin = PureShear.nargin

    #PureShear computes and plots displacement paths and progressive finite
#strain history for pure shear with maximum stretching parallel to the 
#X1 axis
    
    #   USE: [paths,pfs] = PureShear(pts,st1,ninc)
    
    #   pts: npoints x 2 matrix with X1 and X3 locations of points
#   st1 = Maximum principal stretch
#   ninc = number of strain increments
#   paths = displacement paths of points
#   pfs = progressive finite strain history. column 1 = orientation of
#         maximum stretch with respect to X1 in degrees, column 2 = maximum
#         stretch magnitude
    
    #   NOTE: Intermediate principal stretch is 1.0 (Plane strain)
#         Output orientations are in radians
    
    #MATLAB script written by Nestor Cardozo for the book Structural 
#Geology Algorithms by Allmendinger, Cardozo, & Fisher, 2011. If you use
#this script, please cite this as "Cardozo in Allmendinger et al. (2011)"
    
    #Compute minimum principal stretch and incremental stretches
    st1inc=st1 ** (1.0 / ninc)
# PureShear.m:24
    st3=1.0 / st1
# PureShear.m:25
    st3inc=st3 ** (1.0 / ninc)
# PureShear.m:26
    #Initialize displacement paths
    npts=size(pts,1)
# PureShear.m:29
    
    paths=zeros(npts,2,ninc + 1)
# PureShear.m:30
    paths[:,:,1]=pts
# PureShear.m:31
    
    #Calculate incremental deformation gradient tensor
    F=matlabarray(cat([(st1inc),0.0],[0.0(st3inc)]))
# PureShear.m:34
    #Create a figure and hold
    figure
    hold('on')
    #Compute displacement paths
    for i in arange(1,npts).reshape(-1):
        for j in arange(2,ninc + 1).reshape(-1):
            #Equations 10.2-10.5
            for k in arange(1,2).reshape(-1):
                for L in arange(1,2).reshape(-1):
                    paths[i,k,j]=dot(F[k,L],paths[i,L,j - 1]) + paths[i,k,j]
# PureShear.m:46
        #Plot displacement path of point. Use MATLAB function squeeze to reduce
    #the 3D matrix to one vector in X1 and another in X3
        xx=squeeze(paths[i,1,:])
# PureShear.m:52
        yy=squeeze(paths[i,2,:])
# PureShear.m:53
        plot(xx,yy,'k.-')
    
    #Release plot and set axes
    hold('off')
    axis('equal')
    xlabel('X1')
    ylabel('X3')
    grid('on')
    #Initalize progressive finite strain history
    pfs=zeros(ninc + 1,2)
# PureShear.m:64
    pfs[1,:]=cat(0,1.0)
# PureShear.m:65
    
    #Calculate progressive finite strain history
    for i in arange(1,ninc).reshape(-1):
        #First determine the finite deformation gradient tensor
        finF=F ** i
# PureShear.m:70
        G=dot(finF,finF.T)
# PureShear.m:72
        #corresponding eigenvectors of Green's tensor. Use MATLAB function eig
        V,D=eig(G,nargout=2)
# PureShear.m:75
        pfs[i + 1,1]=atan(V[2,2] / V[1,2])
# PureShear.m:76
        pfs[i + 1,2]=sqrt(D[2,2])
# PureShear.m:77
    
    #Plot progressive finite strain history
    figure
    plot(dot(pfs[:,1],180) / pi,pfs[:,2],'k.-')
    xlabel('Theta finite deg')
    ylabel('Maximum finite stretch')
    axis(cat(- 90,90,1,max(pfs[:,2]) + 0.5))
    grid('on')
    return paths,pfs
    
if __name__ == '__main__':
    pass
    