# Autogenerated with SMOP 
from smop.core import *
# SuppeEquation.m

    
@function
def SuppeEquation(gama=None,theta=None,*args,**kwargs):
    varargin = SuppeEquation.varargin
    nargin = SuppeEquation.nargin

    #SuppeEquation: First equation in Eq. 11.8 for fault bend folding
    
    #MATLAB script written by Nestor Cardozo for the book Structural 
#Geology Algorithms by Allmendinger, Cardozo, & Fisher, 2011. If you use
#this script, please cite this as "Cardozo in Allmendinger et al. (2011)"
    
    y=sin(dot(2,gama)) / (dot(2,(cos(gama)) ** 2) + 1) - tan(theta)
# SuppeEquation.m:8
    return y
    
if __name__ == '__main__':
    pass
    