# Autogenerated with SMOP 
from smop.core import *
# CorrSpher.m

    
@function
def CorrSpher(xp=None,yp=None,laj=None,*args,**kwargs):
    varargin = CorrSpher.varargin
    nargin = CorrSpher.nargin

    #CorrSpher calculates the correlation matrix for a spherical variogram
    
    #   USE: r=CorrSpher(xp,yp,laj)
    
    #   xp = vector with x locations of points along bed
#   yp = vector with y locations of points along bed
#   laj = correlation length
#   r = correlation matrix
    
    #MATLAB script written by Nestor Cardozo for the book Structural 
#Geology Algorithms by Allmendinger, Cardozo, & Fisher, 2011. If you use
#this script, please cite this as "Cardozo in Allmendinger et al. (2011)"
    
    #Number of points along bed
    nj=max(size(xp))
# CorrSpher.m:16
    #Initialize correlation matrix
    r=zeros(nj,nj)
# CorrSpher.m:19
    #Compute correlation matrix
    for i in arange(1,nj).reshape(-1):
        for j in arange(1,nj).reshape(-1):
            #Find distance v between points i and j along bed
            v=0.0
# CorrSpher.m:25
            minind=min(i,j)
# CorrSpher.m:26
            maxind=max(i,j)
# CorrSpher.m:27
            for k in arange(minind,maxind - 1,1).reshape(-1):
                v=v + sqrt((xp[k] - xp[k + 1]) ** 2 + (yp[k] - yp[k + 1]) ** 2)
# CorrSpher.m:29
            #Compute variogram entry
            h=v / laj
# CorrSpher.m:32
            if h < 1.0:
                r[i,j]=1.0 + dot(0.5,(dot(- 3,h) + h ** 3))
# CorrSpher.m:35
    
    return r
    
if __name__ == '__main__':
    pass
    