# Autogenerated with SMOP 
from smop.core import *
# GeogrToView.m

    
@function
def GeogrToView(trd=None,plg=None,trdv=None,plgv=None,*args,**kwargs):
    varargin = GeogrToView.varargin
    nargin = GeogrToView.nargin

    #GeogrToView transforms a line from NED to View Direction
#coordinates
    
    #   USE: [rtrd,rplg] = GeogrToView(trd,plg,trdv,plgv)
    
    #   trd = trend of line
#   plg = plunge of line 
#   trdv = trend of view direction 
#   plgv = plunge of view direction 
#   rtrd and rplg are the new trend and plunge of the line in the view
#   direction.
    
    #   NOTE: Input/Output angles are in radians
    
    #   GeogrToView uses functions ZeroTwoPi, SphToCart and CartToSph
    
    #MATLAB script written by Nestor Cardozo for the book Structural 
#Geology Algorithms by Allmendinger, Cardozo, & Fisher, 2011. If you use
#this script, please cite this as "Cardozo in Allmendinger et al. (2011)"
    
    #Some constants
    east=pi / 2.0
# GeogrToView.m:23
    # Make transformation matrix between NED and View Direction
    a=zeros(3,3)
# GeogrToView.m:26
    a[3,1],a[3,2],a[3,3]=SphToCart(trdv,plgv,0,nargout=3)
# GeogrToView.m:27
    temp1=trdv + east
# GeogrToView.m:28
    temp2=0.0
# GeogrToView.m:29
    a[2,1],a[2,2],a[2,3]=SphToCart(temp1,temp2,0,nargout=3)
# GeogrToView.m:30
    temp1=copy(trdv)
# GeogrToView.m:31
    temp2=plgv - east
# GeogrToView.m:32
    a[1,1],a[1,2],a[1,3]=SphToCart(temp1,temp2,0,nargout=3)
# GeogrToView.m:33
    # Direction cosines of line
    dirCos=zeros(1,3)
# GeogrToView.m:36
    dirCos[1],dirCos[2],dirCos[3]=SphToCart(trd,plg,0,nargout=3)
# GeogrToView.m:37
    # Transform line
    nDirCos=zeros(1,3)
# GeogrToView.m:40
    for i in arange(1,3).reshape(-1):
        nDirCos[i]=dot(a[i,1],dirCos[1]) + dot(a[i,2],dirCos[2]) + dot(a[i,3],dirCos[3])
# GeogrToView.m:42
    
    # Compute line from new direction cosines
    rtrd,rplg=CartToSph(nDirCos[1],nDirCos[2],nDirCos[3],nargout=2)
# GeogrToView.m:46
    # Take care of negative plunges
    if rplg < 0.0:
        rtrd=ZeroTwoPi(rtrd + pi)
# GeogrToView.m:50
        rplg=- rplg
# GeogrToView.m:51
    
    return rtrd,rplg
    
if __name__ == '__main__':
    pass
    