# Autogenerated with SMOP 
# SphToCart.m
import math
import numpy 
    
def SphToCart(trd=None,plg=None,k=None,*args,**kwargs):
    # varargin = SphToCart.varargin
    # nargin = SphToCart.nargin

    #SphToCart converts from spherical to cartesian coordinates
    
    #   [cn,ce,cd] = SphToCart(trd,plg,k) returns the north (cn), 
#   east (ce), and down (cd) direction cosines of a line.
    
    #   k is an integer to tell whether the trend and plunge of a line 
#   (k = 0) or strike and dip of a plane in right hand rule 
#   (k = 1) are being sent in the trd and plg slots. In this 
#   last case, the direction cosines of the pole to the plane 
#   are returned
    
    #   NOTE: Angles should be entered in radians
    
    #MATLAB script written by Nestor Cardozo for the book Structural 
#Geology Algorithms by Allmendinger, Cardozo, & Fisher, 2011. If you use
#this script, please cite this as "Cardozo in Allmendinger et al. (2011)"
    
    #If line (see Table 2.1)
    if k == 0:
        cd=math.sin(plg)
# SphToCart.m:21
        ce=numpy.dot(math.cos(plg),math.sin(trd))
# SphToCart.m:22
        cn=numpy.dot(math.cos(plg),math.cos(trd))
# SphToCart.m:23
        #Else pole to plane (see Table 2.1)
    else:
        if k == 1:
            cd=math.cos(plg)
# SphToCart.m:26
            ce=numpy.dot(- math.sin(plg),math.cos(trd))
# SphToCart.m:27
            cn=numpy.dot(math.sin(plg),math.sin(trd))
# SphToCart.m:28
    
    return cn,ce,cd
    
if __name__ == '__main__':
    pass
    