# Autogenerated with SMOP 
from smop.core import *
# SuppeEquationTwo.m

    
@function
def SuppeEquationTwo(gamstar=None,ramp=None,*args,**kwargs):
    varargin = SuppeEquationTwo.varargin
    nargin = SuppeEquationTwo.nargin

    #SuppeEquationTwo: First equation in Eq.11.20 for parallel fault 
#propagation folding
    
    #MATLAB script written by Nestor Cardozo for the book Structural 
#Geology Algorithms by Allmendinger, Cardozo, & Fisher, 2011. If you use
#this script, please cite this as "Cardozo in Allmendinger et al. (2011)"
    
    y=(1.0 + dot(dot(2.0,cos(gamstar)),cos(gamstar))) / sin(dot(2.0,gamstar)) + (cos(ramp) - 2.0) / sin(ramp)
# SuppeEquationTwo.m:9
    return y
    
if __name__ == '__main__':
    pass
    