# Autogenerated with SMOP 
from smop.core import *
# Transpose.m

    
@function
def Transpose(a=None,*args,**kwargs):
    varargin = Transpose.varargin
    nargin = Transpose.nargin

    #Transpose calculates the transpose of a matrix
    
    #   USE: c = Transpose(a)
    
    #   The original matrix is a; the transpose of a is returned in c
    
    #   NOTE: This function is only for illustration purposes. To get the
#   transpose of a matrix in MATLAB use the ' operator (e.g. c = a')
    
    #MATLAB script written by Nestor Cardozo for the book Structural 
#Geology Algorithms by Allmendinger, Cardozo, & Fisher, 2011. If you use
#this script, please cite this as "Cardozo in Allmendinger et al. (2011)"
    
    #Number of rows and columns in a
    n=size(a,1)
# Transpose.m:16
    m=size(a,2)
# Transpose.m:17
    #Initialize c. Note the switch of number of rows and columns here
    c=zeros(m,n)
# Transpose.m:19
    for i in arange(1,n).reshape(-1):
        for j in arange(1,m).reshape(-1):
            c[j,i]=a[i,j]
# Transpose.m:23
    
    return c
    
if __name__ == '__main__':
    pass
    