# Autogenerated with SMOP 
from smop.core import *
# ZeroTwoPi.m

    
@function
def ZeroTwoPi(a=None,*args,**kwargs):
    varargin = ZeroTwoPi.varargin
    nargin = ZeroTwoPi.nargin

    #ZeroTwoPi constrains azimuth to lie between 0 and 2*pi radians
    
    #   b = ZeroTwoPi(a) returns azimuth b (from 0 to 2*pi)
#   for input azimuth a (which may not be between 0 to 2*pi)
    
    #   NOTE: Azimuths a and b are input/output in radians
    
    #MATLAB script written by Nestor Cardozo for the book Structural 
#Geology Algorithms by Allmendinger, Cardozo, & Fisher, 2011. If you use
#this script, please cite this as "Cardozo in Allmendinger et al. (2011)"
    
    b=copy(a)
# ZeroTwoPi.m:13
    twopi=dot(2.0,pi)
# ZeroTwoPi.m:14
    if b < 0.0:
        b=b + twopi
# ZeroTwoPi.m:16
    else:
        if b >= twopi:
            b=b - twopi
# ZeroTwoPi.m:18
    
    return b
    
if __name__ == '__main__':
    pass
    