# Autogenerated with SMOP 
# ZeroTwoPi.m
import math 
import numpy

def calculate_trend_less_than_zero(trend, twopi):
    return trend + twopi

def calculate_trend_greater_than_twopi(trend,twopi):
    return trend - twopi 
    
def ZeroTwoPi(a=None,*args,**kwargs):
    # varargin = ZeroTwoPi.varargin
    # nargin = ZeroTwoPi.nargin

    #ZeroTwoPi constrains azimuth to lie between 0 and 2*pi radians
    
    #   b = ZeroTwoPi(a) returns azimuth b (from 0 to 2*pi)
#   for input azimuth a (which may not be between 0 to 2*pi)
    
    #   NOTE: Azimuths a and b are input/output in radians
    
    #MATLAB script written by Nestor Cardozo for the book Structural 
#Geology Algorithms by Allmendinger, Cardozo, & Fisher, 2011. If you use
#this script, please cite this as "Cardozo in Allmendinger et al. (2011)"
    b=a

    twopi=numpy.dot(2.0,math.pi)
    if b < 0.0:
        b = calculate_trend_less_than_zero(b, twopi)
    else:
        if b >= twopi:
            b = calculate_trend_greater_than_twopi(b, twopi)
            
    return b
    
if __name__ == '__main__':
    pass
    